import { Beer } from './models/index';

export const BEERS: Beer[] = [
  {
    id: 1,
    name: 'Buzz',
    tagline: 'A Real Bitter Experience.',
    first_brewed: '09/2007',
    description:
      'A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.',
    image_url: 'https://images.punkapi.com/v2/keg.png',
    abv: 4.5,
    ibu: 60,
    target_fg: 1010,
    target_og: 1044,
    ebc: 20,
    srm: 10,
    ph: 4.4,
    attenuation_level: 75,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Spicy chicken tikka masala',
      'Grilled chicken quesadilla',
      'Caramel toffee cake',
    ],
  },
  {
    id: 2,
    name: 'Trashy Blonde',
    tagline: "You Know You Shouldn't",
    first_brewed: '04/2008',
    description:
      'A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say? The seductive lure of the sassy passion fruit hop proves too much to resist. All that is even before we get onto the fact that there are no additives, preservatives, pasteurization or strings attached. All wrapped up with the customary BrewDog bite and imaginative twist.',
    image_url: 'https://images.punkapi.com/v2/2.png',
    abv: 4.1,
    ibu: 41.5,
    target_fg: 1010,
    target_og: 1041.7,
    ebc: 15,
    srm: 15,
    ph: 4.4,
    attenuation_level: 76,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Fresh crab with lemon',
      'Garlic butter dipping sauce',
      'Goats cheese salad',
      'Creamy lemon bar doused in powdered sugar',
    ],
  },
  {
    id: 3,
    name: 'Berliner Weisse With Yuzu - B-Sides',
    tagline: 'Japanese Citrus Berliner Weisse.',
    first_brewed: '11/2015',
    description:
      'Japanese citrus fruit intensifies the sour nature of this German classic.',
    image_url: 'https://images.punkapi.com/v2/keg.png',
    abv: 4.2,
    ibu: 8,
    target_fg: 1007,
    target_og: 1040,
    ebc: 8,
    srm: 4,
    ph: 3.2,
    attenuation_level: 83,
    volume: { value: 20, unit: 'litres' },
    food_pairing: ['Smoked chicken wings', 'Miso ramen', 'Yuzu cheesecake'],
  },
  {
    id: 4,
    name: 'Pilsen Lager',
    tagline: 'Unleash the Yeast Series.',
    first_brewed: '09/2013',
    description:
      'Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Pilsner yeast ferments with no fruity esters or spicy phenols, although it can add a hint of butterscotch.',
    image_url: 'https://images.punkapi.com/v2/4.png',
    abv: 6.3,
    ibu: 55,
    target_fg: 1012,
    target_og: 1060,
    ebc: 30,
    srm: 15,
    ph: 4.4,
    attenuation_level: 80,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Spicy crab cakes',
      'Spicy cucumber and carrot Thai salad',
      'Sweet filled dumplings',
    ],
  },
  {
    id: 5,
    name: 'Avery Brown Dredge',
    tagline: "Bloggers' Imperial Pilsner.",
    first_brewed: '02/2011',
    description:
      'An Imperial Pilsner in collaboration with beer writers. Tradition. Homage. Revolution. We wanted to showcase the awesome backbone of the Czech brewing tradition, the noble Saaz hop, and also tip our hats to the modern beers that rock our world, and the people who make them.',
    image_url: 'https://images.punkapi.com/v2/5.png',
    abv: 7.2,
    ibu: 59,
    target_fg: 1027,
    target_og: 1069,
    ebc: 10,
    srm: 5,
    ph: 4.4,
    attenuation_level: 67,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Vietnamese squid salad',
      'Chargrilled corn on the cob with paprika butter',
      'Strawberry and rhubarb pie',
    ],
  },
  {
    id: 6,
    name: 'Electric India',
    tagline: 'Vibrant Hoppy Saison.',
    first_brewed: '05/2013',
    description:
      'Re-brewed as a spring seasonal, this beer – which appeared originally as an Equity Punk shareholder creation – retains its trademark spicy, fruity edge. A perfect blend of Belgian Saison and US IPA, crushed peppercorns and heather honey are also added to produce a genuinely unique beer.',
    image_url: 'https://images.punkapi.com/v2/6.png',
    abv: 5.2,
    ibu: 38,
    target_fg: 1005,
    target_og: 1045,
    ebc: 15,
    srm: 7.5,
    ph: 4.4,
    attenuation_level: 88.9,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Mussels with a garlic and herb sauce',
      'Crab melt sandwich',
      'Shortbread cookies',
    ],
  },
  {
    id: 7,
    name: 'AB:12',
    tagline: 'Imperial Black Belgian Ale.',
    first_brewed: '07/2012',
    description:
      'An Imperial Black Belgian Ale aged in old Invergordon Scotch whisky barrels with mountains of raspberries, tayberries and blackberries in each cask. Decadent but light and dry, this beer would make a fantastic base for ageing on pretty much any dark fruit - we used raspberries, tayberries and blackberries beause they were local.',
    image_url: 'https://images.punkapi.com/v2/7.png',
    abv: 11.2,
    ibu: 35,
    target_fg: 1017,
    target_og: 1108,
    ebc: 80,
    srm: 40,
    ph: 5.3,
    attenuation_level: 84,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Tandoori lamb with pomegranate',
      'Beef Wellington with a red wine jus',
      'Raspberry chocolate torte',
    ],
  },
  {
    id: 8,
    name: 'Fake Lager',
    tagline: 'Bohemian Pilsner.',
    first_brewed: '03/2013',
    description:
      'Fake is the new black. Fake is where it is at. Fake Art, fake brands, fake breasts, and fake lager. We want to play our part in the ugly fallout from the Lager Dream. Say hello to Fake Lager – a zesty, floral 21st century faux masterpiece with added BrewDog bitterness.',
    image_url: 'https://images.punkapi.com/v2/8.png',
    abv: 4.7,
    ibu: 40,
    target_fg: 1010,
    target_og: 1046,
    ebc: 12,
    srm: 6,
    ph: 4.4,
    attenuation_level: 78,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Fried crab cakes with avocado salsa',
      'Spicy shredded pork roll with hot dipping sauce',
      'Key lime pie',
    ],
  },
  {
    id: 9,
    name: 'AB:07',
    tagline: 'Whisky Cask-Aged Scotch Ale.',
    first_brewed: '03/2010',
    description:
      'Whisky cask-aged imperial scotch ale. Beer perfect for when the rain is coming sideways. Liquorice, plum and raisin temper the warming alcohol, producing a beer capable of holding back the Scottish chill.',
    image_url: 'https://images.punkapi.com/v2/9.png',
    abv: 12.5,
    ibu: 30,
    target_fg: 1020,
    target_og: 1106,
    ebc: 84,
    srm: 42,
    ph: 5.6,
    attenuation_level: 83,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Kedgeree',
      'Scotch broth with sourdough bread',
      'Clootie dumpling',
    ],
  },
  {
    id: 10,
    name: 'Bramling X',
    tagline: 'Single Hop IPA Series - 2011.',
    first_brewed: '01/2011',
    description:
      'Good old Bramling Cross is elegant, refined, assured, (boring) and understated. Understated that is unless you hop the living daylights out of a beer with it. This is Bramling Cross re-invented and re-imagined, and shows just what can be done with English hops if you use enough of them. Poor Bramling Cross normally gets lost in a woeful stream of conformist brown ales made by sleepy cask ale brewers. But not anymore. This beer shows that British hops do have some soul, and is a fruity riot of blackberries, pears, and plums. Reminds me of the bramble, apple and ginger jam my grandmother used to make.',
    image_url: 'https://images.punkapi.com/v2/10.png',
    abv: 7.5,
    ibu: 75,
    target_fg: 1013,
    target_og: 1068,
    ebc: 22,
    srm: 11,
    ph: 4.4,
    attenuation_level: 80.9,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Warm blackberry pie',
      'Vinegar doused fish and chips',
      'Aromatic korma curry with lemon and garlic naan',
    ],
  },
  {
    id: 11,
    name: 'Misspent Youth',
    tagline: 'Milk & Honey Scotch Ale.',
    first_brewed: '04/2013',
    description:
      'The brainchild of our small batch brewer, George Woods. A dangerously drinkable milk sugar- infused Scotch Ale.',
    image_url: 'https://images.punkapi.com/v2/keg.png',
    abv: 7.3,
    ibu: 30,
    target_fg: 1020,
    target_og: 1079,
    ebc: 120,
    srm: 60,
    ph: 4.4,
    attenuation_level: 74.7,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Roasted garlic and chilli infused camembert cheese',
      'Korean style chicken wings',
      'Chocolate milk shake',
    ],
  },
  {
    id: 12,
    name: 'Arcade Nation',
    tagline: 'Seasonal Black IPA.',
    first_brewed: '12/2015',
    description:
      'Running the knife-edge between an India Pale Ale and a Stout, this particular style is one we truly love. Black IPAs are a great showcase for the skill of our brew team, balancing so many complex and twisting flavours in the same moment. The citrus, mango and pine from the hops – three of our all-time favourites – play off against the roasty dryness from the malt bill at each and every turn.',
    image_url: 'https://images.punkapi.com/v2/12.png',
    abv: 5.3,
    ibu: 60,
    target_fg: 1012,
    target_og: 1052,
    ebc: 200,
    srm: 100,
    ph: 4.2,
    attenuation_level: 77,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'King prawn kebabs',
      'Halibut with a mango and tomato salad',
      'Mint chocloate ice cream',
    ],
  },
  {
    id: 13,
    name: 'Movember',
    tagline: 'Moustache-Worthy Beer.',
    first_brewed: '11/2009',
    description:
      'A deliciously robust, black malted beer with a decadent dark, dry cocoa flavour that provides an enticing backdrop to the Cascade hops.',
    image_url: 'https://images.punkapi.com/v2/13.png',
    abv: 4.5,
    ibu: 50,
    target_fg: 1012,
    target_og: 1047,
    ebc: 140,
    srm: 70,
    ph: 5.2,
    attenuation_level: 74.5,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Vegetable egg scramble',
      'Margherita pizza',
      'Fresh berry crisp tart',
    ],
  },
  {
    id: 14,
    name: 'Alpha Dog',
    tagline: 'Existential Red Ale.',
    first_brewed: '02/2010',
    description:
      'A fusion of caramel malt flavours and punchy New Zealand hops. A session beer you can get your teeth into.',
    image_url: 'https://images.punkapi.com/v2/14.png',
    abv: 4.5,
    ibu: 42,
    target_fg: 1025,
    target_og: 1046,
    ebc: 62,
    srm: 31,
    ph: 4.4,
    attenuation_level: 72.8,
    volume: { value: 20, unit: 'litres' },
    food_pairing: [
      'Pastrami',
      'Swiss and horseradish sandwich',
      'Sharp cheddar cheese and onion/ raisin chutney',
      'Peanut brittle',
    ],
  },
];
